<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>ChessAnalyzer.Stockfish</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ChessAnalyzer.Core\ChessAnalyzer.Core.csproj" />
  </ItemGroup>

</Project>
